# Generated by Django 3.2.4 on 2021-06-03 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(default=60)),
                ('expected_status', models.IntegerField(default=200)),
                ('users', models.TextField(blank=True, default=None, null=True)),
                ('failed_status', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UrlStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('time_checked', models.DateTimeField()),
                ('state', models.BooleanField(default=False)),
                ('url_tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='urltrack.urltracker')),
            ],
        ),
    ]
