# Generated by Django 3.2.3 on 2021-05-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urltrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urltracker',
            name='account',
        ),
    ]
