# Generated by Django 3.2.4 on 2021-06-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urltrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltracker',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
