# Generated by Django 3.2.4 on 2021-06-03 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urltrack', '0002_alter_urltracker_admin_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urltracker',
            old_name='admin_emails',
            new_name='admin_email',
        ),
    ]
