# Generated by Django 3.2.3 on 2021-05-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urltrack', '0003_auto_20210531_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltracker',
            name='status_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='urltracker',
            name='time_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
