# Generated by Django 3.2.3 on 2021-05-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urltrack', '0004_auto_20210531_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltracker',
            name='expected_status',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='urltracker',
            name='frequency',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='urltracker',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
